### ISSUE TITLE
[BUG] Settings menu bottom not completely visible when it's too long

### ISSUE THREAD

**Issue by Porkepix** [FoedusProgramme/Gramophone#54]
**Describe the bug**
Settings menu can slide when it's short and shouldn't be able to, and when it's long enough the very bottom is partially hidden

**To Reproduce**
Just visit settings with this release

**Expected behavior**
We shouldn't be able to slide from settings menu short enough, and should be able to see everything when it's long enough.

**Screenshots**

<details>
<summary>
Screenshots
</summary>

This one is short enough, see on first screenshot. Despite that, you can slide and end up in the state of second screenshot.
![Screenshot_20231203-173342](https://github.com/AkaneTan/Gramophone/assets/709500/32eeb7dc-053e-465c-9658-d3ad861281a5)
![Screenshot_20231203-173345](https://github.com/AkaneTan/Gramophone/assets/709500/a71274e8-936f-4f4f-ae21-797d3dc021dc)

That one is long enough, and the very bottom is partially hidden
![Screenshot_20231203-173311](https://github.com/AkaneTan/Gramophone/assets/709500/d94a7849-f601-4dc0-ba3a-5151d4619326)

</details>

**Smartphone (please complete the following information):**
 - Device: Xperia XZ
 - OS: Android Oreo 8.0
 - Release from https://github.com/AkaneTan/Gramophone/issues/37#issuecomment-1837493118

**Comment by nift4** [comment]
The sliding is intentional design behaviour by Google, the bottom being cut off is a bug though.

**Comment by Porkepix** [comment]
> The sliding is intentional design behaviour by Google, the bottom being cut off is a bug though.

Imho, you shouldn't be allowed to slide if everything fits in one screen. But if that's the design choices of Google and you wanna stick to that, well, can't do anything about it I guess.

**Comment by AkaneTan** [comment]
Resolved in https://github.com/AkaneTan/Gramophone/commit/f31f7d078d6ba09006b7453666359aa033f3960c.

**Comment by nift4** [comment]
keep it open as reminder for me to look into root cause

**Comment by AkaneTan** [comment]
> keep it open as reminder for me to look into root cause

There's no such root cause. In legacy MD there's no such thing like "edge-to-edge" display and back then preference's recyclerview looks fine simply because the app is displayed with system bars' padding applied naturally. Now we have edge-to-edge but google still haven't updated their preference library.

**Comment by nift4** [comment]
Yes, but that shouldn't be solved with dummy preferences - we can dynamically get system bar padding and apply it, which will work properly

**Comment by Porkepix** [comment]
> There's no such root cause. In legacy MD there's no such thing like "edge-to-edge" display and back then preference's recyclerview looks fine simply because the app is displayed with system bars' padding applied naturally.

What's legacy MD?

**Comment by nift4** [comment]
Legacy Material Design - i.e. Android 5~7/8

**Comment by Porkepix** [comment]
> Legacy Material Design - i.e. Android 5~7/8

Eh, I wish there was some preference and that it'd be some kind of theming in frameworks/system: personal preferences, but I preferred previous themes/guidelines compared to most recent ones.

**Comment by nift4** [comment]
fixed 8216019

**Comment by Porkepix** [comment]
@nift4 Running https://github.com/AkaneTan/Gramophone/releases/tag/1.0.4.1 I still have a comparable issues: can't see the bottom of long menus, and can slide down the shortest ones.

**Comment by nift4** [comment]
The sliding is intentional design behaviour by Google.

I am not able to reproduce the issue on emulator, can you please send a screen record or recording of your phone using a camera?

**Comment by Porkepix** [comment]
> The sliding is intentional design behaviour by Google.

I thought you said this could be worked around with some padding in https://github.com/AkaneTan/Gramophone/issues/54#issuecomment-1876784673? Or I completely misunderstood and it was about the other issue, which would make sense.
Still thinking this behavior is really not normal.

> I am not able to reproduce the issue on emulator, can you please send a screen record or recording of your phone using a camera?

Record will be difficult, but below are screenshots taken on some (all?) of the problematic screens scrolled at the lowest possible position.

<details>
<summary>
Screenshots
</summary>

![Screenshot_20240219-164418](https://github.com/AkaneTan/Gramophone/assets/709500/fae88e01-1a11-4cef-9401-7406b96d4ab9)
![Screenshot_20240219-164427](https://github.com/AkaneTan/Gramophone/assets/709500/7b6c24af-8e4b-463f-abf9-6b44787819a4)
![Screenshot_20240219-164442](https://github.com/AkaneTan/Gramophone/assets/709500/ae2ff7df-8640-4eb5-a8e7-7ff1cdccb66a)

</details>

**Comment by nift4** [comment]
hmm thanks, i can see it's still related to inset handling, but the emulator doesn't like me. I'll see what I can do

**Comment by nift4** [comment]
[Gramophone-1.0.4.1.c72ab5-release.apk.zip](https://github.com/AkaneTan/Gramophone/files/14334826/Gramophone-1.0.4.1.c72ab5-release.apk.zip)

**Comment by Porkepix** [comment]
> [Gramophone-1.0.4.1.c72ab5-release.apk.zip](https://github.com/AkaneTan/Gramophone/files/14334826/Gramophone-1.0.4.1.c72ab5-release.apk.zip)

The part about the hidden bottom is indeed fixed with that build.
